Fix build error on clear rebuild
When rebuilding textmate from scratch:

git clean -xffd; git reset --hard HEAD; rm -rf ~/build/TextMate/; ./configure; ninja

This error appears:

Frameworks/OakAppKit/src/OakTabBarView.mm:7:9: fatal error: 'OakAppKit/OakFileIconImage.h' file not found

After one issues "ninja" again, textmate continues building fine.

I guess this might be because perhaps OakAppKit's headers are being copied
to the build include directory (~/build/TextMate/include) in parallel when
building OakTabBarView.mm. No matter what actually is the case, this patch
fixes building during clean build.